.ifndef HARDWARE_INC
    .define HARDWARE_INC 1

;***************************************************************************
;*
;* Keypad related
;*
;***************************************************************************

.define PADF_UP     $01
.define PADF_DOWN   $02
.define PADF_LEFT   $04
.define PADF_RIGHT  $08
.define PADF_A      $10
.define PADF_B      $20
.define PADF_START  $80

.define PADB_UP     $0
.define PADB_DOWN   $1
.define PADB_LEFT   $2
.define PADB_RIGHT  $3
.define PADB_A      $4
.define PADB_B      $5
.define PADB_START  $7

.endif
