#!/usr/bin/env ruby
# frozen_string_literal: true

require "digest"
require "fileutils"
require "open3"
require "pathname"
require_relative "catalog_lib"

if ARGV.length != 2
  warn "usage: #{$PROGRAM_NAME} <manifest.mk> <output-stamp>"
  exit 64
end

manifest_path, output_path = ARGV
project_root = Pathname.new(File.expand_path("..", __dir__))

repo_root_stdout, status = Open3.capture2("git", "-C", project_root.to_s, "rev-parse", "--show-toplevel")
unless status.success?
  warn "not inside a git repository"
  exit 1
end
repo_root = Pathname.new(repo_root_stdout.strip)

def repo_relative(repo_root, path)
  Pathname.new(path).expand_path.relative_path_from(repo_root).to_s
end

def git_output(repo_root, *args)
  stdout, status = Open3.capture2("git", "-C", repo_root.to_s, *args)
  [stdout, status.success?]
end

def git_tracked?(repo_root, path)
  rel = repo_relative(repo_root, path)
  _stdout, ok = git_output(repo_root, "ls-files", "--error-unmatch", "--", rel)
  ok
end

def git_has_tracked_files?(repo_root, path)
  rel = repo_relative(repo_root, path)
  rel = "#{rel}/" unless rel.end_with?("/")
  stdout, ok = git_output(repo_root, "ls-files", "--", rel)
  ok && !stdout.lines.empty?
end

def sha256(path)
  Digest::SHA256.file(path).hexdigest
end

def snowbro_release_number(path)
  match = File.read(path).match(/SNOWBRO[\s-]+(\d+)/i)
  raise "missing SNOWBRO NNN header string: #{path}" if match.nil?

  Integer(match[1], 10)
end

def write_if_changed(path, bytes)
  current = File.exist?(path) ? File.binread(path) : nil
  return false if current == bytes

  FileUtils.mkdir_p(File.dirname(path))
  tmp = "#{path}.tmp.#{$PROCESS_ID}"
  File.binwrite(tmp, bytes)
  File.rename(tmp, path)
  true
end

SUPPORTED_SOURCE_ASSEMBLERS = ["rgbasm", "wla-gb"].freeze

songs = CatalogLib.load_manifest(project_root + manifest_path)
prefix_owners = {}
bank_owners = {}
release_number_owners = {}
release_numbers = []
stamp_lines = ["# Generated by tools/verify_sources.rb; do not edit."]

begin
  songs.each do |song|
    if prefix_owners.key?(song.prefix)
      raise "#{song.slug}: duplicate label prefix #{song.prefix.inspect} " \
            "also used by #{prefix_owners.fetch(song.prefix)}"
    end
    prefix_owners[song.prefix] = song.slug

    if song.bank < 1
      raise "#{song.slug}: song bank must be greater than zero: #{song.bank}"
    end
    if bank_owners.key?(song.bank)
      raise "#{song.slug}: duplicate song bank #{song.bank} " \
            "also used by #{bank_owners.fetch(song.bank)}"
    end
    bank_owners[song.bank] = song.slug

    source_dir = project_root + song.source
    unless git_has_tracked_files?(repo_root, source_dir)
      raise "#{song.slug}: source project has no tracked files: #{source_dir}"
    end

    makefile = source_dir + "Makefile"
    raise "#{song.slug}: Makefile is not tracked: #{makefile}" unless git_tracked?(repo_root, makefile)
    unless SUPPORTED_SOURCE_ASSEMBLERS.include?(song.source_assembler)
      raise "#{song.slug}: unsupported source assembler #{song.source_assembler.inspect}"
    end
    unless File.read(makefile).include?(song.source_assembler)
      raise "#{song.slug}: Makefile does not contain #{song.source_assembler}"
    end
    stamp_lines << "#{song.slug} makefile #{repo_relative(repo_root, makefile)} #{sha256(makefile)}"

    files = [
      ["xm", source_dir + song.xm],
      ["instruments", source_dir + song.instruments],
      ["song_asm", source_dir + song.song_asm],
      ["main_asm", source_dir + song.main_asm]
    ]

    files.each do |kind, path|
      raise "#{song.slug}: source asset is not tracked: #{path}" unless git_tracked?(repo_root, path)

      stamp_lines << "#{song.slug} #{kind} #{repo_relative(repo_root, path)} #{sha256(path)}"
    end

    release_number = snowbro_release_number(source_dir + song.main_asm)
    if release_number_owners.key?(release_number)
      raise "#{song.slug}: duplicate SNOWBRO #{format('%03d', release_number)} " \
            "also used by #{release_number_owners.fetch(release_number)}"
    end
    release_number_owners[release_number] = song.slug
    release_numbers << [song.slug, release_number]
    stamp_lines << "#{song.slug} snowbro #{format('%03d', release_number)}"
  end

  sorted_release_numbers = release_numbers.sort_by { |_slug, number| number }
  unless release_numbers == sorted_release_numbers
    expected_order = sorted_release_numbers.map do |slug, number|
      "#{format('%03d', number)} #{slug}"
    end.join(", ")
    raise "SONGS order must follow SNOWBRO chronology: #{expected_order}"
  end

  write_if_changed(project_root + output_path, (stamp_lines.join("\n") + "\n").b)
  puts "verified #{songs.length} source song project(s)"
rescue StandardError => e
  warn e.message
  exit 1
end
